addr: :8080
host: 127.0.0.1
RUNMODE: release
jwt_secret: boGhzDJ61jLy9FuMJWKuzfNtGyq5qEql
aes_secret: qsc8102neC9f3KFC
grpc_addr: 10.202.68.181:8890
wechat:
  AppID: wxdb99a92837c753dd
  AppSecret: 7ed11d82aa16a9f32fd860107d5f045a
db:
  name: miniprogram
  addr: db2.zjuqsc.com
  username: miniprogram
  password: 4CAq7OUQ4JUFwkdH
#db:
#  name: wechat
#  addr: 127.0.0.1:3306
#  username: root
#  password: root
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/qscwechat.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7