addr: :8080
RUNMODE: release
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/qscwechat.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7