addr: :8080
host: 127.0.0.1
RUNMODE: release
jwt_secret:
wechat:
  AppID:
  AppSecret:
db:
  name: wechat
  addr: 127.0.0.1:3306
  username:
  password:
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/qscwechat.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7